### ISSUE TITLE
Launch file for node?

### ISSUE THREAD

**Issue by kk6axq** [ros-teleop/teleop_tools#10]
Hi,
I am trying to use your node and I notice that there isn't any launch file nor are there instructions on how to launch the package. Is it just a hidden secret on how to launch this or...

**Comment by bmagyar** [comment]
Or I was lazy to finish the documentation, yes you have won! :)

Which node are you trying to launch? 
You could get away by using a launch file like this: https://github.com/pal-robotics/reem_robot/blob/hydro-devel/reem_bringup/launch/joystick_teleop.launch

**Comment by kk6axq** [comment]
I am trying launch the joy teleport node with a chided 360 controller. Is
there a launch file already written with that configuration?
Thanks,
KK6AXQ

**Comment by bmagyar** [comment]
I am not familiar with that joystick. Does the joy_node work with it?
joy_teleop is subscribing to the /joy topic to provide high level
functionalities. Unless you have a driver for your joystick it won't do any
good.

Try using `jstest /dev/?` to see if your Linux support the joystick device
at all.

**Comment by kk6axq** [comment]
I am trying to use a Xbox 360 controller. I think auto correct messed it up...

----- Reply message -----

**Comment by po1** [comment]
@kk6axq on linux the kernel should have native support for that joystick. The ROS driver is called `joy`, you need to start it with `rosrun joy joy_node` before you can use `joy_teleop`. `joy_teleop` will map joystick inputs to ROS topics and actions, have a look in the `config/joy_teleop.yaml` file to learn more.

The canonical way to start `joy_teleop` is to run `rosrun joy_teleop joy_teleop.py`

**Comment by bmagyar** [comment]
Hello,

In the latest release I've added an example launch file and config file for joy_teleop to the install rules too, so even users not coming here will have easy access to them.
This concludes this issue, happy teleoping!
