### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by veimox** [ros-teleop/teleop_tools#26]
I was wondering what are the release plans for melodic. I have cloned the repo and it compiles without problems. I have tested `key_teleop` and is working too.

**Comment by bmagyar** [comment]
Could you please test the others too? Any simulation test will do fine.

I can push a release no problem but won't be able to test them on melodic
anytime soon...

**Comment by bmagyar** [comment]
Thanks for the ping, I'm pushing a melodic release.
Feel free to get back to us here with PR-s you'd like to see or bug reports

**Comment by bmagyar** [comment]
Here's the release PR: https://github.com/ros/rosdistro/pull/19520
After the merge & buildfarm steps it should be available from shadow-fixed repos, available from upstream apt after the next sync. Please feel free to get back to us should anything be missing.
