### ISSUE TITLE
Branch melodic-devel disappeared? 

### ISSUE THREAD

**Issue by LPitonakova** [ros-teleop/teleop_tools#36]
Hi,
I was previously using branch melodic-devel but git pull on it started failing today. I also checked your branches on github and it seems like the branch is no longer there - could you please advise what to do?

**Comment by bmagyar** [comment]
Hi,
Yes indeed, I removed that branch yesterday as it was only an outdated version of the kinetic branch while releases were also only made from the kinetic branch. If you have changed made in the melodic branch it is fairly safe to rebase them to Kinetic.

**Comment by LPitonakova** [comment]
Hi, thanks for your answer. I am using ROS melodic with Ubuntu 18.04, wouldn't using the kinetic branch create conflicts? Or does your kinetic branch support both melodic and kinetic?

**Comment by bmagyar** [comment]
It supports both.

**Comment by bmagyar** [comment]
I will close this issue for now, please feel free to reopen if you find issues.
