### ISSUE TITLE
installing package from ros-testing broken

### ISSUE THREAD

**Issue by ToffeeAlbina-TRI** [ros-teleop/teleop_tools#37]
sudo apt-get install ros-dashing-teleop-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  ros-dashing-joy-teleop ros-dashing-key-teleop ros-dashing-teleop-tools-msgs ros-dashing-trajectory-msgs
The following NEW packages will be installed:
  ros-dashing-joy-teleop ros-dashing-key-teleop ros-dashing-teleop-tools ros-dashing-teleop-tools-msgs
  ros-dashing-trajectory-msgs
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/390 kB of archives.
After this operation, 4,335 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Selecting previously unselected package ros-dashing-teleop-tools-msgs.
(Reading database ... 390962 files and directories currently installed.)
Preparing to unpack .../ros-dashing-teleop-tools-msgs_1.0.0-0bionic.20190911.135253_amd64.deb ...
Unpacking ros-dashing-teleop-tools-msgs (1.0.0-0bionic.20190911.135253) ...
Selecting previously unselected package ros-dashing-trajectory-msgs.
Preparing to unpack .../ros-dashing-trajectory-msgs_0.7.0-1bionic.20190911.145240_amd64.deb ...
Unpacking ros-dashing-trajectory-msgs (0.7.0-1bionic.20190911.145240) ...
Selecting previously unselected package ros-dashing-joy-teleop.
Preparing to unpack .../ros-dashing-joy-teleop_1.0.0-0bionic.20190911.145914_amd64.deb ...
Unpacking ros-dashing-joy-teleop (1.0.0-0bionic.20190911.145914) ...
Preparing to unpack .../ros-dashing-key-teleop_1.0.0-0bionic.20190911.142910_amd64.deb ...
Unpacking ros-dashing-key-teleop (1.0.0-0bionic.20190911.142910) ...
dpkg: error processing archive /var/cache/apt/archives/ros-dashing-key-teleop_1.0.0-0bionic.20190911.142910_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/dashing/lib/python3.6/site-packages/scripts/__init__.py', which is also in package ros-dashing-joy-teleop 1.0.0-0bionic.20190911.145914
Selecting previously unselected package ros-dashing-teleop-tools.
Preparing to unpack .../ros-dashing-teleop-tools_1.0.0-0bionic.20190911.145955_amd64.deb ...
Unpacking ros-dashing-teleop-tools (1.0.0-0bionic.20190911.145955) ...
Errors were encountered while processing:
 /var/cache/apt/archives/ros-dashing-key-teleop_1.0.0-0bionic.20190911.142910_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by bmagyar** [comment]
FYI @artivis

**Comment by artivis** [comment]
I'm having a similar issue,
```terminal
Unpacking ros-dashing-joy-teleop (1.0.0-0bionic.20190911.145914) ...
dpkg: error processing archive /var/cache/apt/archives/ros-dashing-joy-teleop_1.0.0-0bionic.20190911.145914_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/dashing/lib/python3.6/site-packages/scripts/__init__.py', which is also in package ros-dashing-gazebo-ros 3.3.3-1bionic.20190908.063412
```
Looking into it.

**Comment by artivis** [comment]
A breaking change happened in [ament_index](https://github.com/ament/ament_index/issues/33) during the course of the port. Fixing teleop_tools asap.

**Comment by dirk-thomas** [comment]
> A breaking change happened in colcon-ros, (see e.g. ament_index) during the course of the port.

The above error has nothing to do with the referenced change in `colcon-ros`. These packages simply install their scripts incorrectly.

**Comment by artivis** [comment]
Install rules were fixed in #38. I could successfully install all of the tools from ros-testing.  
@ToffeeAlbina-TRI Do you mind giving the installation another try?  

@bmagyar This issue can be closed.

**Comment by bmagyar** [comment]
Thanks @Arnatious  and @artivis for the fix! Closing...

**Comment by ToffeeAlbina-TRI** [comment]
Verified fixed.  Thanks @artivis
