### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [ros-teleop/teleop_tools#51]
Would you mind releasing these packages also for the newest distribution ROS Noetic? :)

Maybe after #43?

**Comment by bmagyar** [comment]
Have you given it a shot yet? I don't have a full setup for noetic atm, can
only do some builds in a container

**Comment by Timple** [comment]
No I did not.
We are missing quite some dependencies for our bots so I've pinged most of them like this. I won't switch to a 20.04 system until at least all dependencies build or are released.
I've created a PR that at passes the prerelease tests.

**Comment by davetcoleman** [comment]
MoveIt is also blocked by this release. Do we have an estimate for when this can be released?
https://github.com/ros-planning/moveit/issues/2015

**Comment by bmagyar** [comment]
Working on it ATM

**Comment by bmagyar** [comment]
Quick test on a local docker image revealed a couple of issues, a few I fixed already, a few remain:
https://github.com/ros-teleop/teleop_tools/pull/53

If urgent, please fire your own PR-s to my `noetic-updates` branch

**Comment by bmagyar** [comment]
I think we can work with this now, please provide me some reviews: https://github.com/ros-teleop/teleop_tools/pull/53/files

I've tested them in a container, the mouse teleop glitch is possibly coming from the container context, not an actual error.

**Comment by bmagyar** [comment]
Once again, thank you lads for flagging this up, I think the release I pushed out should be fully functional. If it isn't, feel free to get back to us with PR-s ;) 

https://github.com/ros/rosdistro/pull/25329
