### ISSUE TITLE
ROS2 releases

### ISSUE THREAD

**Issue by bmagyar** [ros-teleop/teleop_tools#56]
@clalancette which distros would you like me to push releases to? Eloquent & Foxy?

**Comment by clalancette** [comment]
> @clalancette which distros would you like me to push releases to? Eloquent & Foxy?

Foxy and Rolling is mostly what I care about at this point.  Eloquent is a bonus if you feel like doing it.

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/26994

**Comment by bmagyar** [comment]
bloom didn't want to pick 1.2 for eloquent on it's own on the new release so I opted to not push it :)

**Comment by clalancette** [comment]
> bloom didn't want to pick 1.2 for eloquent on it's own on the new release so I opted to not push it :)

That's OK, that one wasn't that important to me anyway (and it goes out of support in just over a month).

Thanks so much for doing the releases!

**Comment by bmagyar** [comment]
No worries, feel free to make an announcement is you'd like.
