### ISSUE TITLE
Compilation in ROS Melodic

### ISSUE THREAD

**Issue by GeneralAdmin** [ros-teleop/teleop_tools#68]
Compilation in ROS Melodic

Hi!
When I try to compile it in melodic, i get the error bellow. Has anyone seen this before? 

viki@viki:~/catkin_ws$ catkin build
---------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/viki/catkin_ws
---------------------------------------------------------
Build Space:        [exists] /home/viki/catkin_ws/build
Devel Space:        [exists] /home/viki/catkin_ws/devel
Install Space:      [unused] /home/viki/catkin_ws/install
Log Space:          [exists] /home/viki/catkin_ws/logs
Source Space:       [exists] /home/viki/catkin_ws/src
DESTDIR:            [unused] None
---------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
---------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
---------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
---------------------------------------------------------
Workspace configuration appears valid.
---------------------------------------------------------
[build] Found '18' packages in 0.0 seconds.                                    
[build] Package table is up to date.                                           
[build] Warning: Skipping package `key_teleop` because it has an unsupported package build type: `ament_python`
[build] Note: Available build types:                                           
[build]  - `catkin`                                                            
[build]  - `cmake`                                                             
[build] Warning: Skipping package `mouse_teleop` because it has an unsupported package build type: `ament_python`
[build] Note: Available build types:                                           
[build]  - `catkin`                                                            
[build]  - `cmake`                                                             
[build] Warning: Skipping package `teleop_tools` because it has an unsupported package build type: `ament_cmake`
[build] Note: Available build types:                                           
[build]  - `catkin`                                                            
[build]  - `cmake`                                                             
[build] Warning: Skipping package `teleop_tools_msgs` because it has an unsupported package build type: `ament_cmake`
[build] Note: Available build types:                                           
[build]  - `catkin`                                                            
[build]  - `cmake`                                                             
Abandoned <<< bebop_tools                         [ Depends on unknown jobs: teleop_tools_msgs ]
Abandoned <<< joy_teleop                          [ Depends on unknown jobs: teleop_tools_msgs ]
Starting  >>> avoidance                                                        
Starting  >>> bebop_description                                                
Starting  >>> bebop_msgs                                                       
Starting  >>> planers                                                          
Starting  >>> point_cloud_io                                                   
Starting  >>> pplanner                                                         
Starting  >>> simulador_uav                                                    
Finished  <<< bebop_description                   [ 2.2 seconds ]              
Finished  <<< planers                             [ 5.4 seconds ]              
Finished  <<< point_cloud_io                      [ 6.4 seconds ]              
Finished  <<< simulador_uav                       [ 14.8 seconds ]             
Finished  <<< bebop_msgs                          [ 15.9 seconds ]             
Starting  >>> bebop_driver                                                     
Finished  <<< pplanner                            [ 15.8 seconds ]             
Finished  <<< avoidance                           [ 15.9 seconds ]             
Starting  >>> global_planner                                                   
Starting  >>> local_planner                                                    
Starting  >>> safe_landing_planner                                             
Finished  <<< bebop_driver                        [ 3.1 seconds ]              
Finished  <<< safe_landing_planner                [ 8.3 seconds ]              
Finished  <<< global_planner                      [ 8.8 seconds ]              
Finished  <<< local_planner                       [ 8.8 seconds ]              
[build] Summary: 11 of 13 packages succeeded.                                  
[build]   Ignored:   5 packages were skipped or are blacklisted.               
[build]   Warnings:  None.                                                     
[build]   Abandoned: 2 packages were abandoned.                                
[build]   Failed:    None.                                                     
[build] Runtime: 26.1 seconds total.

**Comment by bmagyar** [comment]
Check the branch
Check if you need to compile this from source at all, installing should just work

**Comment by GeneralAdmin** [comment]
> Check the branch
> Check if you need to compile this from source at all, installing should just work

Installing worked offcourse! Thks!

**Comment by McGrady-175** [comment]
> Check the branch Check if you need to compile this from source at all, installing should just work

thank you very much!
